### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by ghost** [icculus/mojoshader#40]
Hi, I face this problem on arm (Aarch64)

/usr/bin/ld: cannot find -lobjc
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/glcaps.dir/build.make:85: glcaps] Error 1
make[1]: *** [CMakeFiles/Makefile2:284: CMakeFiles/glcaps.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

what dep I missed here?

**Comment by flibitijibibo** [comment]
You didn't disable Metal. Also, based on other reports, you are either trying to build FNA3D or an older version of MojoShader that won't have the ABI you're looking for.
