### ISSUE TITLE
Shader that works with spir-v output fails with glsl output

### ISSUE THREAD

**Issue by thatcosmonaut** [icculus/mojoshader#41]
https://gist.github.com/thatcosmonaut/ea211fddaeba4c5f7541cb583bde945e

This palette crush shader works fine with spir-v output, but it only samples the leftmost pixel on glsl output. As you can see, in the glsl output the loop never increments the texcoord.

**Comment by flibitijibibo** [comment]
Seems like it gets incremented here?

https://gist.github.com/thatcosmonaut/ea211fddaeba4c5f7541cb583bde945e#file-mojoshader_glsl_output-L34

r1.x is (1 / PaletteWidth) and r1.y is set to 0, then gets incremented by 1 at the end of the block. So each texture2D() should be sampling at the correct spot for each iteration.

**Comment by thatcosmonaut** [comment]
You are right... there must be some reason why the shader isn't working though...

**Comment by flibitijibibo** [comment]
Check it with something like LLVMpipe, if it fails there too it's probably the shader, otherwise it's probably radeonsi.

**Comment by thatcosmonaut** [comment]
Fails on Windows D3D11 too so I must be doing something bad.

**Comment by thatcosmonaut** [comment]
`#define FLT_MAX 3.402823466e+38`

This was the culprit. Don't do this.
