### ISSUE TITLE
CMake is looking for `../Vulkan-Headers/`

### ISSUE THREAD

**Issue by icculus** [icculus/mojoshader#46]
Can we look for these in a standard place, or just include them with the MojoShader sources?

**Comment by flibitijibibo** [comment]
Will page @thatcosmonaut in case he's aware of any known trick, but the source of this is us simply including Vulkan-Headers in the parent project:

https://github.com/FNA-XNA/FNA3D

Bundling the headers directly can cause conflicts with the renderer that uses MojoShader, and unlike GL/ the headers for Vulkan are... kind of huge.

I would suggest:
- Start with ../Vulkan-Headers for local builds
- If it doesn't exist, search for system headers (I want to say find_package but that function is awful and probably does a search for libvulkan.so too)
- Error if neither exist

**Comment by thatcosmonaut** [comment]
I agree with that strategy.

**Comment by flibitijibibo** [comment]
Fixed via https://github.com/icculus/mojoshader/commit/9bfd475023e7ca74568fd105ebad3e33195f2aab
